### ISSUE TITLE
Data format for surveys?

### ISSUE THREAD

**Issue by eappell** [cdeng/angularFire-survey#2]
I like the way you've setup this app, but I'm trying to find some documentation for how the data should be structured in firebase for the surveys?  Is there an object map or sample dataset somewhere that shows how I should structure the data so it pulls it into the app for surveys?  

Thanks!

**Comment by cdeng** [comment]
Hello, thank you for your feedback.  Here is a sample dataset that shows you the structure I am using in this particular app.

``` json
"surveys" : {
    "-Joz6dDzuwFCv48P9swy" : {
      "age" : "30-",
      "colors" : {
        "blue" : true,
        "green" : false,
        "red" : false
      },
      "comment" : "Thank you.",
      "lunch" : true,
      "name" : "Your Name",
      "rating" : 5,
      "timestamp" : 1431283070947
    },
    "-JozAbBG8Z2mDhwJOYfz" : {
      "age" : "30-",
      "colors" : {
        "blue" : true,
        "green" : false,
        "red" : false
      },
      "comment" : "Thank you.",
      "lunch" : true,
      "name" : "Your Name",
      "rating" : 5,
      "timestamp" : 1431284111129
    }
}
```

The data structure was created in [line 29](https://github.com/cdeng/angularFire-survey/blob/master/app/js/controllers.js#L29) of /app/js/controller.js.  

I don't know what exactly you are trying to do, so I am not sure if the answer above helps.  Are you trying to do something with your existing data?  For example, someone uses this app to build a tool that categorizes comments (i.e. adding labels/tags to each existing comment).  In that case, this structure doesn't work since this structure contains random IDs generated by Firebase for each entry.  The workaround is tweaking the controller.js a little bit, and using [$firebaseArray](https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-firebasearray) to build an array for your existing data and new responses you are trying to collect.

Thanks,
CD

**Comment by eappell** [comment]
That's perfect, thank you.  I want to use it as a survey app, and knowing where the location of the data structure is helps a great deal.  I can now go and tweak it the way I need.  Thanks again!
